"use client";

import { useCallback, useEffect, useState } from "react";
import { ROLE_LABELS, type Role } from "@/types";

type Account = { id: string; full_name: string; email: string; phone: string | null; role: Role; account_status: string; force_password_reset: boolean; created_at: string; updated_at: string; last_sign_in_at: string | null };
type Stats = { total: number; active: number; inactive: number; suspended: number; deleted: number; incomplete: number; admin: number; coach: number; parent: number };
const roles: Role[] = ["admin", "coach", "parent"];
const emptyStats: Stats = { total: 0, active: 0, inactive: 0, suspended: 0, deleted: 0, incomplete: 0, admin: 0, coach: 0, parent: 0 };

function date(value: string | null) { return value ? new Date(value).toLocaleString("id-ID") : "Belum pernah"; }

export default function AccountManagement() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [stats, setStats] = useState<Stats>(emptyStats);
  const [recentActivity, setRecentActivity] = useState<{ id: string; action: string; created_at: string }[]>([]);
  const [q, setQ] = useState("");
  const [role, setRole] = useState("ALL");
  const [status, setStatus] = useState("ALL");
  const [sort, setSort] = useState("newest");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [editing, setEditing] = useState<Account | null>(null);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ full_name: "", email: "", phone: "", role: "parent" as Role, password: "", force_password_reset: true });

  const load = useCallback(async () => {
    const params = new URLSearchParams({ q, role, status, sort });
    const res = await fetch(`/api/admin/accounts?${params}`);
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Gagal memuat akun");
    setAccounts(data.accounts); setStats(data.stats); setRecentActivity(data.recentActivity || []);
  }, [q, role, status, sort]);
  useEffect(() => { load().catch((e) => setMessage(`✗ ${e.message}`)); }, [load]);
  function resetForm() { setForm({ full_name: "", email: "", phone: "", role: "parent", password: "", force_password_reset: true }); setCreating(false); setEditing(null); }
  async function request(path: string, options: RequestInit) { setBusy(true); setMessage(null); try { const res = await fetch(path, options); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Operasi gagal"); setMessage("✓ Perubahan tersimpan"); await load(); resetForm(); } catch (e) { setMessage(`✗ ${e instanceof Error ? e.message : "Operasi gagal"}`); } finally { setBusy(false); } }
  function createAccount(e: React.FormEvent) { e.preventDefault(); return request("/api/admin/accounts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); }
  function updateAccount(e: React.FormEvent) { e.preventDefault(); if (!editing) return; if (form.role !== editing.role && !window.confirm(`Ubah role akun ${editing.full_name} menjadi ${ROLE_LABELS[form.role]}?`)) return; return request("/api/admin/accounts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing.id, action: "update", full_name: form.full_name, email: form.email, phone: form.phone, role: form.role, force_password_reset: form.force_password_reset, account_status: editing.account_status }) }); }
  function password(e: React.FormEvent) { e.preventDefault(); if (!editing) return; return request("/api/admin/accounts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing.id, action: "set_password", password: form.password, force_password_reset: form.force_password_reset }) }); }
  function action(id: string, name: string, label: string) { if (!window.confirm(`${label}?`)) return; return request("/api/admin/accounts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: name }) }); }
  function startEdit(account: Account) { setEditing(account); setCreating(false); setForm({ full_name: account.full_name, email: account.email, phone: account.phone || "", role: account.role, password: "", force_password_reset: account.force_password_reset }); }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Account Management</h1><p className="text-sm text-slate-500">Kelola akun Supabase Auth, role, status, dan keamanan akun.</p></div><button className="btn-primary" onClick={() => { resetForm(); setCreating(true); }}>+ Buat Akun</button></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Total Akun" value={stats.total}/><Stat label="Aktif" value={stats.active}/><Stat label="Nonaktif" value={stats.inactive + stats.suspended}/><Stat label="Belum Lengkap" value={stats.incomplete}/><Stat label="Admin" value={stats.admin}/><Stat label="Coach" value={stats.coach}/><Stat label="Parent" value={stats.parent}/><Stat label="Terhapus" value={stats.deleted}/></div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="card"><h2 className="mb-3 font-semibold">Akun terbaru</h2><ul className="space-y-2 text-sm">{accounts.slice(0,5).map(a => <li key={a.id} className="flex justify-between gap-3"><span className="truncate">{a.full_name}</span><span className="whitespace-nowrap text-xs text-slate-500">{date(a.created_at)}</span></li>)}</ul></div><div className="card"><h2 className="mb-3 font-semibold">Aktivitas akun terbaru</h2><ul className="space-y-2 text-sm">{recentActivity.slice(0,5).map(a => <li key={a.id} className="flex justify-between gap-3"><span className="font-medium">{a.action}</span><span className="whitespace-nowrap text-xs text-slate-500">{date(a.created_at)}</span></li>)}{recentActivity.length === 0 && <li className="text-slate-400">Belum ada aktivitas akun.</li>}</ul></div></div>
    {(creating || editing) && <div className="card space-y-4"><div className="flex justify-between"><h2 className="font-semibold">{creating ? "Buat Akun Baru" : `Edit: ${editing?.full_name}`}</h2><button className="text-sm text-slate-500" onClick={resetForm}>Tutup</button></div><form onSubmit={creating ? createAccount : updateAccount} className="grid gap-3 md:grid-cols-2"><label className="label">Nama<input className="input" required value={form.full_name} onChange={e => setForm({...form, full_name:e.target.value})}/></label><label className="label">Email<input className="input" type="email" required value={form.email} onChange={e => setForm({...form, email:e.target.value})}/></label><label className="label">WhatsApp<input className="input" value={form.phone} onChange={e => setForm({...form, phone:e.target.value})}/></label><label className="label">Role<select className="input" value={form.role} onChange={e => setForm({...form, role:e.target.value as Role})}>{roles.map(r => <option key={r} value={r}>{ROLE_LABELS[r]}</option>)}</select></label>{creating && <label className="label">Password<input className="input" type="password" minLength={8} required value={form.password} onChange={e => setForm({...form, password:e.target.value})}/></label>}<label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" checked={form.force_password_reset} onChange={e => setForm({...form, force_password_reset:e.target.checked})}/> Wajib ganti password pada login berikutnya</label><button disabled={busy} className="btn-primary md:col-span-2">{busy ? "Menyimpan..." : creating ? "Buat Akun" : "Simpan Profil"}</button></form>{editing && <form onSubmit={password} className="border-t border-slate-200 pt-4"><h3 className="mb-2 font-medium">Reset Password</h3><div className="flex flex-wrap gap-2"><input className="input max-w-sm" type="password" minLength={8} placeholder="Password baru, min. 8 karakter" value={form.password} onChange={e => setForm({...form, password:e.target.value})}/><button disabled={busy || form.password.length < 8} className="btn-secondary">Reset Password</button></div><p className="mt-2 text-xs text-slate-500">Password tidak pernah ditampilkan atau disimpan di database aplikasi.</p></form>}</div>}
    <div className="card space-y-3"><div className="grid gap-2 md:grid-cols-4"><input className="input" placeholder="Cari nama, email, WhatsApp" value={q} onChange={e => setQ(e.target.value)}/><select className="input" value={role} onChange={e => setRole(e.target.value)}><option value="ALL">Semua role</option>{roles.map(r => <option key={r} value={r}>{ROLE_LABELS[r]}</option>)}</select><select className="input" value={status} onChange={e => setStatus(e.target.value)}><option value="ALL">Semua status</option><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option><option value="SUSPENDED">Suspended</option><option value="DELETED">Deleted</option></select><select className="input" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="name_asc">Nama A-Z</option><option value="name_desc">Nama Z-A</option></select></div>{message && <p className={`rounded-lg px-3 py-2 text-sm ${message.startsWith("✓") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{message}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="px-3 py-2">Nama</th><th className="px-3 py-2">Email</th><th className="px-3 py-2">Role</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Login terakhir</th><th className="px-3 py-2">Aksi</th></tr></thead><tbody className="divide-y">{accounts.map(a => <tr key={a.id}><td className="px-3 py-2 font-medium">{a.full_name}</td><td className="px-3 py-2">{a.email || "—"}</td><td className="px-3 py-2">{ROLE_LABELS[a.role] || a.role}</td><td className="px-3 py-2"><span className={`badge ${a.account_status === "ACTIVE" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{a.account_status}{a.force_password_reset ? " · RESET" : ""}</span></td><td className="px-3 py-2 text-slate-500">{date(a.last_sign_in_at)}</td><td className="px-3 py-2"><div className="flex flex-wrap gap-1"><button className="btn-secondary px-2 py-1 text-xs" onClick={() => startEdit(a)}>Edit</button>{a.account_status === "ACTIVE" ? <button className="btn-secondary px-2 py-1 text-xs" onClick={() => action(a.id,"disable","Nonaktifkan akun ini")}>Disable</button> : <button className="btn-secondary px-2 py-1 text-xs" onClick={() => action(a.id,"enable","Aktifkan akun ini")}>Enable</button>}{a.account_status !== "DELETED" ? <button className="btn-danger px-2 py-1 text-xs" onClick={() => action(a.id,"delete","Soft delete akun ini")}>Delete</button> : <button className="btn-secondary px-2 py-1 text-xs" onClick={() => action(a.id,"restore","Restore akun ini")}>Restore</button>}</div></td></tr>)}{accounts.length === 0 && <tr><td colSpan={6} className="px-3 py-8 text-center text-slate-400">Tidak ada akun sesuai filter.</td></tr>}</tbody></table></div></div>
  </div>;
}
function Stat({label,value}:{label:string;value:number}) { return <div className="card p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-brand-700">{value}</p></div>; }
