"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function PaymentSettingsForm({ initial }: { initial?: { bank_name?: string | null; account_number?: string | null; account_name?: string | null; ewallet_name?: string | null; ewallet_number?: string | null; instructions?: string | null } | null }) {
  const supabase = createClient(); const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ bank_name: initial?.bank_name ?? "", account_number: initial?.account_number ?? "", account_name: initial?.account_name ?? "", ewallet_name: initial?.ewallet_name ?? "", ewallet_number: initial?.ewallet_number ?? "", instructions: initial?.instructions ?? "" });
  const set = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }));
  async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(null); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Sesi login berakhir."); setSaving(false); return; } const { error: saveError } = await supabase.from("payment_settings").upsert({ id: true, ...form, updated_by: user.id, updated_at: new Date().toISOString() }); if (saveError) setError(saveError.message); else router.refresh(); setSaving(false); }
  return <form onSubmit={save} className="card space-y-4"><h2 className="font-semibold">Payment Settings</h2><p className="text-sm text-slate-500">Rekening hanya tampil setelah admin mengonfigurasinya.</p><div className="grid gap-4 sm:grid-cols-2"><label className="label">Bank<input className="input" value={form.bank_name} onChange={(e) => set("bank_name", e.target.value)} placeholder="BCA / Mandiri" /></label><label className="label">Nomor rekening<input className="input" value={form.account_number} onChange={(e) => set("account_number", e.target.value)} /></label><label className="label">Nama rekening<input className="input" value={form.account_name} onChange={(e) => set("account_name", e.target.value)} /></label><label className="label">E-wallet<input className="input" value={form.ewallet_name} onChange={(e) => set("ewallet_name", e.target.value)} placeholder="GoPay / DANA" /></label><label className="label">Nomor e-wallet<input className="input" value={form.ewallet_number} onChange={(e) => set("ewallet_number", e.target.value)} /></label><label className="label sm:col-span-2">Instruksi pembayaran<textarea className="input" rows={3} value={form.instructions} onChange={(e) => set("instructions", e.target.value)} /></label></div>{error && <p className="text-sm text-red-700">{error}</p>}<button disabled={saving} className="btn-primary">{saving ? "Menyimpan..." : "Simpan Payment Settings"}</button></form>;
}
