"use client";

import { useState } from "react";

export default function PaymentSettingsForm({ initial }: { initial?: { bank_name?: string | null; account_number?: string | null; account_name?: string | null; ewallet_name?: string | null; ewallet_number?: string | null; instructions?: string | null; bank_transfer_enabled?: boolean; ewallet_enabled?: boolean; cash_enabled?: boolean } | null }) {
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [form, setForm] = useState({ bank_name: initial?.bank_name ?? "", account_number: initial?.account_number ?? "", account_name: initial?.account_name ?? "", ewallet_name: initial?.ewallet_name ?? "", ewallet_number: initial?.ewallet_number ?? "", instructions: initial?.instructions ?? "", bank_transfer_enabled: initial?.bank_transfer_enabled ?? true, ewallet_enabled: initial?.ewallet_enabled ?? true, cash_enabled: initial?.cash_enabled ?? false });
  const set = (key: keyof typeof form, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(null); setSaved(false); try { const res = await fetch("/api/admin/payment-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Gagal menyimpan"); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : "Gagal menyimpan payment settings"); } finally { setSaving(false); } }
  return <form onSubmit={save} className="card space-y-4"><h2 className="font-semibold">Payment Settings</h2><p className="text-sm text-slate-500">Hanya Admin yang dapat mengubah konfigurasi ini. Rekening dan metode aktif dipakai untuk instruksi pembayaran.</p><div className="grid gap-4 sm:grid-cols-2"><label className="label">Bank<input className="input" value={form.bank_name} onChange={(e) => set("bank_name", e.target.value)} placeholder="BCA / Mandiri" /></label><label className="label">Nomor rekening<input className="input" value={form.account_number} onChange={(e) => set("account_number", e.target.value)} /></label><label className="label">Nama rekening<input className="input" value={form.account_name} onChange={(e) => set("account_name", e.target.value)} /></label><label className="label">Provider e-wallet<input className="input" value={form.ewallet_name} onChange={(e) => set("ewallet_name", e.target.value)} placeholder="GoPay / DANA" /></label><label className="label">Nomor e-wallet<input className="input" value={form.ewallet_number} onChange={(e) => set("ewallet_number", e.target.value)} /></label><label className="label sm:col-span-2">Instruksi pembayaran<textarea className="input" rows={3} value={form.instructions} onChange={(e) => set("instructions", e.target.value)} /></label></div><fieldset><legend className="label">Metode pembayaran aktif</legend><div className="flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={form.bank_transfer_enabled} onChange={(e) => set("bank_transfer_enabled", e.target.checked)} /> Transfer bank</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.ewallet_enabled} onChange={(e) => set("ewallet_enabled", e.target.checked)} /> E-wallet</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.cash_enabled} onChange={(e) => set("cash_enabled", e.target.checked)} /> Tunai</label></div></fieldset>{error && <p className="text-sm text-red-700">{error}</p>}{saved && <p className="text-sm text-emerald-700">✓ Payment settings tersimpan dan tercatat di audit log.</p>}<button disabled={saving} className="btn-primary">{saving ? "Menyimpan..." : "Simpan Payment Settings"}</button></form>;
}
