"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function RelayTeamForm({ eventId, races, athletes }: { eventId: string; races: Array<{ id: string; name: string; is_relay: boolean }>; athletes: Array<{ id: string; full_name: string; birth_date: string | null }> }) {
  const relayRaces = races.filter((r) => r.is_relay); const supabase = createClient(); const router = useRouter(); const [raceId, setRaceId] = useState(relayRaces[0]?.id ?? ""); const [teamName, setTeamName] = useState(""); const [members, setMembers] = useState<string[]>(["", "", "", ""]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  if (!relayRaces.length) return null;
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(null); const ids = members.filter(Boolean); if (!teamName.trim() || !raceId || ids.length < 2) { setError("Isi nama tim, nomor estafet, dan minimal 2 anggota."); setSaving(false); return; } if (new Set(ids).size !== ids.length) { setError("Anggota tim tidak boleh duplikat."); setSaving(false); return; } const { data: { user } } = await supabase.auth.getUser(); const { data: team, error: teamError } = await supabase.from("event_relay_teams").insert({ event_id: eventId, race_id: raceId, team_name: teamName.trim(), created_by: user?.id }).select("id").single(); if (teamError) { setError(teamError.message); setSaving(false); return; } const payload = ids.map((athlete_id, index) => ({ relay_team_id: team.id, athlete_id, member_order: index + 1, birth_date_snapshot: athletes.find((a) => a.id === athlete_id)?.birth_date || null })); const { error: memberError } = await supabase.from("event_relay_members").insert(payload); if (memberError) { setError(memberError.message); setSaving(false); return; } router.refresh(); setTeamName(""); setMembers(["", "", "", ""]); setSaving(false); }
  return <form onSubmit={submit} className="card space-y-3"><h2 className="font-semibold">Daftar Tim Estafet</h2><div className="grid gap-3 sm:grid-cols-2"><label className="label">Nomor<select className="input" value={raceId} onChange={(e) => setRaceId(e.target.value)}>{relayRaces.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="label">Nama tim<input className="input" required value={teamName} onChange={(e) => setTeamName(e.target.value)} placeholder="Cakra 1 A" /></label></div><div className="grid gap-2 sm:grid-cols-2">{members.map((value, index) => <select key={index} className="input" value={value} onChange={(e) => setMembers((old) => old.map((x, i) => i === index ? e.target.value : x))}><option value="">Anggota {index + 1}</option>{athletes.map((a) => <option key={a.id} value={a.id}>{a.full_name}</option>)}</select>)}</div>{error && <p className="text-sm text-red-700">{error}</p>}<button disabled={saving} className="btn-secondary">{saving ? "Menyimpan..." : "Simpan Tim Estafet"}</button></form>;
}
